[build-system]
requires = [
    "setuptools>=46.4.0",
    "wheel",
    "Cython>=0.29.21,<3.0",
    'numpy==1.19.1;python_version<"3.10"',
    'numpy;python_version>="3.10"',
]
build-backend = "setuptools.build_meta"
